builds:
  - id: twai
    binary: twai
    main: ./cmd/twai
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - id: twai
    builds:
      - twai
    format: zip
    name_template: 'twai_{{ .Version }}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}'
